# Configuración de perfiles para agentes

defaults: &defaults
  model: gpt-oss-20b
  temperature: 0
  max_tokens: 512
  batch_size: 8
  input_glob: data/prompts/*.jsonl
  output_dir: data/outputs
  analysis_dir: data/analyzed
  findings_dir: data/findings
  timeout_s: 30

profiles:
  mock:
    <<: *defaults
    endpoint: http://127.0.0.1:8000/v1/chat/completions
  gpu-local:
    <<: *defaults
    endpoint: http://127.0.0.1:8000/v1/chat/completions
  gpu-remote:
    <<: *defaults
    endpoint: http://localhost:8000/v1/chat/completions
